POST https://gkyhj54sul.execute-api.us-east-1.amazonaws.com/prod/analyse
Content-Type: application/json

{
  "code": "<?php\nmodule_load_include('inc', 'node', 'node.admin');",
  "level": "9",
  "strictRules": false,
  "bleedingEdge": false,
  "treatPhpDocTypesAsCertain": true,
  "saveResult": true
}

> {%
client.global.set("responseId", response.body.id)
 %}

###

GET https://gkyhj54sul.execute-api.us-east-1.amazonaws.com/prod/result?id={{responseId}}
Accept: application/json
