service: phpstan-drupal-playground-api

provider:
  name: aws
  runtime: nodejs18.x
  architecture: arm64
  stage: prod
  region: us-east-1

plugins:
- serverless-plugin-typescript
- serverless-offline

functions:
  analyseResult:
    handler: handler.analyseResult
    role: arn:aws:iam::994345088675:role/phpstan-drupal-runner-prod-us-east-1-lambdaRole
    events:
    - http:
        method: post
        path: /analyse
        cors: true

  retrieveResult:
    handler: handler.retrieveResult
    role: arn:aws:iam::994345088675:role/phpstan-drupal-runner-prod-us-east-1-lambdaRole
    events:
    - http:
        method: get
        path: /result
        cors: true

  retrieveSample:
    handler: handler.retrieveSample
    role: arn:aws:iam::994345088675:role/phpstan-drupal-runner-prod-us-east-1-lambdaRole
    events:
      - http:
          method: get
          path: /sample
          cors: true

  retrieveLegacyResult:
    handler: handler.retrieveLegacyResult
    role: arn:aws:iam::994345088675:role/phpstan-drupal-runner-prod-us-east-1-lambdaRole
    events:
    - http:
        method: get
        path: /legacyResult
        cors: true
