service: phpstan-drupal-playground-api

provider:
  name: aws
  runtime: nodejs18.x
  architecture: arm64
  stage: prod
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
      Resource: "arn:aws:lambda:us-east-1:994345088675:function:phpstan-drupal-runner-prod-analyze"
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: "arn:aws:s3:::phpstan-drupal-playground/*"

plugins:
- serverless-plugin-typescript
- serverless-offline

functions:
  analyseResult:
    handler: handler.analyseResult
    events:
    - http:
        method: post
        path: /analyse
        cors: true

  retrieveResult:
    handler: handler.retrieveResult
    events:
    - http:
        method: get
        path: /result
        cors: true

  retrieveSample:
    handler: handler.retrieveSample
    events:
      - http:
          method: get
          path: /sample
          cors: true

  retrieveLegacyResult:
    handler: handler.retrieveLegacyResult
    role: arn:aws:iam::994345088675:role/phpstan-drupal-runner-prod-us-east-1-lambdaRole
    events:
    - http:
        method: get
        path: /legacyResult
        cors: true
