service: phpstan-drupal-runner

provider:
  name: aws
  region: us-east-1
  architecture: arm64
  stage: prod
  versionFunctions: false
  httpApi:
    cors: true

plugins:
    - ./vendor/bref/bref

functions:
  analyze:
    handler: analyze.php
    description: ''
    timeout: 28
    runtime: php-81
